[package]
name = "cairo_workshop"
version = "0.1.0"
description = "A minimal template for Cairo 1.0 workshop"
homepage = "https://github.com/finiam/cairo-workshop"

# Uncomment if you want to use dependencies
# Note: currently testing doesn't work with dependencies
# [dependencies]
# quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }
